### ISSUE TITLE
Upgrade kubernetes lib to 29.0 version

### ISSUE THREAD

**Issue by JPugetGil** [VCityTeam/hera_utils#2]
Hera_utils imports a specific version of kubernetes **(k8s)** python client.
This library is platform dependant and needs to be compatible with the deployed k8s version

In our platform, we use kubernetes 1.29
- I need hera_utils use the 29.0.0 version of k8s python library
But be carefull:
read_namespaced_service_account doesn't give the secrets anymore (deprecated).
We should use:
- `read_namespaced_secret` (but it implies to know the name of the secret storing the token and is platform dependant)...
- `create_namespaced_service_account_token` to programatically create a token with the new API

**Comment by EricBoix** [comment]
Kubernets package no longer imported.
Closing
